version: "3.9"
services:
  backend:
    container_name: 'botkit-backend'
    build:
      context: .
    ports:
      - "${APP_PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
      - .env.db
    restart: always
    networks:
      - back
      - default

  mongo:
    container_name: 'botkit-mongodb'
    image: mongo:latest
    restart: always
    env_file:
      - .env.db
    ports:
      - "27017:${MONGO_PORT:-27017}"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    networks:
      - back

networks:
  back:
    driver: bridge
    internal: true

volumes:
  db_data:
  db_config:
