version: "3.9"
services:
  backend-dev:
    container_name: 'botkit-backend-dev'
    build:
      dockerfile: 'Dockerfile-dev'
    ports:
      - "${APP_PORT:-3000}:${PORT:-3000}"
    env_file: .env.dev
    volumes:
      - .:/app/
      - /app/node_modules

  mongo:
    container_name: 'botkit-mongodb'
    image: mongo:latest
    restart: always
    env_file:
      - .env.db
    ports:
      - "27017:${MONGO_PORT:-27019}"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

volumes:
  db_data:
  db_config:
