openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
  /signin:
    post:
      operationId: AuthController_signin
      summary: Войти в систему
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Успешный вход в систему
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProfileDto'
        '401':
          description: Неверное имя пользователя или пароль
      tags: &ref_0
        - auth
  /signup:
    post:
      operationId: AuthController_signup
      summary: Регистрация
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountDto:
                  type: object
                  properties:
                    credentials:
                      type: object
                      properties:
                        password:
                          type: string
                        email:
                          type: string
                profileDto:
                  type: object
                  properties:
                    phone:
                      type: string
                    username:
                      type: string
      responses:
        '201':
          description: Успешная регистрация
        '400':
          description: Некорректные данные
        '409':
          description: Аккаунт уже существует
      tags: *ref_0
  /refresh-token:
    post:
      operationId: AuthController_refreshToken
      summary: Обновить токен
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '201':
          description: accessToken успешно обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: accessToken по умолчанию действует 1 день
                  refreshToken:
                    type: string
                    description: refreshToken по умолчанию действует 7 дней
      tags: *ref_0
  /bots:
    get:
      operationId: BotsController_findMy
      summary: Список ботов пользователя
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_1
        - bots
    post:
      operationId: BotsController_create
      summary: Создание нового бота
      parameters: []
      responses:
        '201':
          description: ''
      tags: *ref_1
  /bots/{id}:
    delete:
      operationId: BotsController_remove
      summary: Удаление бота
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags: *ref_1
    post:
      operationId: BotsController_copy
      summary: Копирование бота
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '201':
          description: ''
      tags: *ref_1
    patch:
      operationId: BotsController_update
      summary: Смена имени бота
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                botName:
                  type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
    get:
      operationId: BotsController_findOne
      summary: Данные бота пользователя
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags: *ref_1
  /bots/{id}/notificationLinks:
    get:
      operationId: BotsController_notificationLinks
      summary: Настройки уведомлений бота
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags: *ref_1
  /bots/{id}/link:
    get:
      operationId: BotsController_getLink
      summary: Ссылка на бота
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      tags: *ref_1
  /bots/{id}/share:
    post:
      operationId: BotsController_share
      summary: Поделиться доступом к боту
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '201':
          description: ''
      tags: *ref_1
  /botTemplates:
    get:
      operationId: botTemplatesController_findAll
      summary: Список шаблонов ботов
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_2
        - botTemplates
  /botTemplates/{id}:
    get:
      operationId: botTemplatesController_findOne
      summary: Данные шаблона бота
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags: *ref_2
  /profiles:
    post:
      operationId: ProfilesController_create
      summary: Создать новый профиль
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProfileDto'
      responses:
        '201':
          description: Профиль успешно создан
        '400':
          description: Некорректные данные
      tags:
        - profiles
        - profiles
    get:
      operationId: ProfilesController_findAll
      parameters: []
      responses:
        '200':
          description: The resources were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
        '403':
          description: Unauthorized Request
      tags: &ref_3
        - profiles
  /profiles/{id}:
    get:
      operationId: ProfilesController_findOne
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор профиля
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      responses:
        '200':
          description: The resource was returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
      tags: *ref_3
    patch:
      operationId: ProfilesController_update
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор профиля
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileDto'
      responses:
        '200':
          description: The resource was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
        '422':
          description: Bad Request
      tags: *ref_3
    delete:
      operationId: ProfilesController_remove
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор профиля
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      responses:
        '200':
          description: The resource was returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
      tags: *ref_3
  /accounts:
    get:
      operationId: AccountController_findAll
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountDto'
      responses:
        '200':
          description: The resources were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '201':
          description: The record has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '403':
          description: Unauthorized Request
      tags: &ref_4
        - Accounts
  /accounts/{id}:
    patch:
      operationId: AccountController_update
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор аккаунта
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccountDto'
      responses:
        '200':
          description: The resource was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
        '422':
          description: Bad Request
      tags: *ref_4
  /platforms:
    post:
      operationId: PlatformController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePlatformDto'
      responses:
        '201':
          description: The record has been successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
      tags: &ref_5
        - Platforms
    get:
      operationId: PlatformController_findAll
      parameters: []
      responses:
        '200':
          description: The resources were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Platform'
        '403':
          description: Unauthorized Request
      tags: *ref_5
  /platforms/{id}:
    get:
      operationId: PlatformController_findOne
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор платформы
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      responses:
        '200':
          description: The resource was returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
      tags: *ref_5
    patch:
      operationId: PlatformController_update
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор платформы
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlatformDto'
      responses:
        '200':
          description: The resource was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
        '422':
          description: Bad Request
      tags: *ref_5
    delete:
      operationId: PlatformController_remove
      parameters:
        - name: id
          required: true
          in: path
          description: Индификатор платформы
          example: 64f81ba37571bfaac18a857f
          schema:
            type: string
      responses:
        '200':
          description: The resource was returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
        '403':
          description: Unauthorized Request
        '404':
          description: Resource not found
      tags: *ref_5
info:
  title: API BotKits
  description: Ручки для команды frontend
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    Credentials:
      type: object
      properties:
        email:
          type: string
          example: my@mail.ru
        password:
          type: string
          example: password123
        accessToken:
          type: string
          example: dkskddksldlslsajsjsdsk,cmksjdksdjskjdk
        refreshToken:
          type: string
          example: dkskddksldlslsajsjsdsk,cmksjdksdjskjdk
      required:
        - email
        - password
        - accessToken
        - refreshToken
    Profile:
      type: object
      properties:
        username:
          type: string
          example: Ivan Ivanov
        phone:
          type: string
          example: '+79501364578'
        avatar:
          type: string
          example: https://i.pravatar.cc/300
        balance:
          type: number
          example: 1400
      required:
        - username
        - phone
        - avatar
        - balance
    Account:
      type: object
      properties:
        type:
          type: string
          example: local
        role:
          type: string
          example: admin
        credentials:
          example:
            email: my@mail.ru
            password: password123
            accessToken: dkskddksldlslsajsjsdsk,cmksjdksdjskjdk
            refreshToken: dkskddksldlslsajsjsdsk,cmksjdksdjskjdk
          allOf:
            - $ref: '#/components/schemas/Credentials'
        profile:
          $ref: '#/components/schemas/Profile'
      required:
        - type
        - role
        - credentials
        - profile
    CreateProfileDto:
      type: object
      properties:
        username:
          type: string
          minLength: 2
          maxLength: 30
          example: Ivan Ivanov
        phone:
          type: string
          example: '+79501364578'
        avatar:
          type: string
          example: https://i.pravatar.cc/300
        balance:
          type: number
          example: 1400
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
      required:
        - username
        - phone
        - accounts
    UpdateProfileDto:
      type: object
      properties:
        username:
          type: string
          minLength: 2
          maxLength: 30
          example: Ivan Ivanov
        phone:
          type: string
          example: '+79501364578'
        avatar:
          type: string
          example: https://i.pravatar.cc/300
        balance:
          type: number
          example: 1400
    ObjectId:
      type: object
      properties: {}
    CreateAccountDto:
      type: object
      properties:
        type:
          enum:
            - local
            - google
            - yandex
            - mail
            - vk
            - ok
            - facebook
            - telegram
          type: string
          example: local
        role:
          enum:
            - user
            - admin
            - superAdmin
          type: string
          example: user
        credentials:
          $ref: '#/components/schemas/Credentials'
        profile:
          example: 64f9ac26edb84d7ebf6281d0
          allOf:
            - $ref: '#/components/schemas/ObjectId'
      required:
        - type
        - role
        - profile
    UpdateAccountDto:
      type: object
      properties:
        type:
          enum:
            - local
            - google
            - yandex
            - mail
            - vk
            - ok
            - facebook
            - telegram
          type: string
          example: local
        role:
          enum:
            - user
            - admin
            - superAdmin
          type: string
          example: admin
        credentials:
          $ref: '#/components/schemas/Credentials'
    FormFields:
      type: object
      properties:
        name:
          type: boolean
          example: true
        pages:
          type: boolean
          example: true
        accessKey:
          type: boolean
          example: false
        url:
          type: boolean
          example: true
      required:
        - name
        - pages
        - accessKey
        - url
    CreatePlatformDto:
      type: object
      properties:
        icon:
          type: string
          example: >-
            https://cdn.icon-icons.com/icons2/1233/PNG/512/1492718766-vk_83600.png
        title:
          type: string
          example: VK
        formFields:
          $ref: '#/components/schemas/FormFields'
      required:
        - icon
        - title
        - formFields
    Platform:
      type: object
      properties:
        icon:
          type: string
          example: >-
            https://cdn.icon-icons.com/icons2/1233/PNG/512/1492718766-vk_83600.png
        title:
          type: string
          example: VK
        formFields:
          example:
            name: true
            pages: true
            accessKey: false
            url: true
          allOf:
            - $ref: '#/components/schemas/FormFields'
      required:
        - icon
        - title
        - formFields
    UpdatePlatformDto:
      type: object
      properties:
        icon:
          type: string
          example: >-
            https://cdn.icon-icons.com/icons2/1233/PNG/512/1492718766-vk_83600.png
        title:
          type: string
          example: VK
        formFields:
          $ref: '#/components/schemas/FormFields'
